#!/usr/bin/env python3
"""
async_comprehension.py

This module provides an asynchronous function to generate a list of floats
using an asynchronous list comprehension.
"""

from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Returns a list of floats generated by the async_generator.

    This function uses an asynchronous list comprehension to gather the results
    from the async_generator and returns them as a list.

    Returns:
        List[float]: A list of floats generated by the async_generator.
    """
    rslt = [i async for i in async_generator()]
    return rslt
